USE [master]
GO

/****** Object:  Database [imoveis]    Script Date: 22/10/2020 18:34:53 ******/
CREATE DATABASE [imoveis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'imoveis', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\imoveis.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'imoveis_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\imoveis_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [imoveis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [imoveis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [imoveis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [imoveis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [imoveis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [imoveis] SET ARITHABORT OFF 
GO

ALTER DATABASE [imoveis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [imoveis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [imoveis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [imoveis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [imoveis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [imoveis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [imoveis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [imoveis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [imoveis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [imoveis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [imoveis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [imoveis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [imoveis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [imoveis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [imoveis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [imoveis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [imoveis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [imoveis] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [imoveis] SET  MULTI_USER 
GO

ALTER DATABASE [imoveis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [imoveis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [imoveis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [imoveis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [imoveis] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [imoveis] SET QUERY_STORE = OFF
GO

ALTER DATABASE [imoveis] SET  READ_WRITE 
GO


